/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.freebitcoin.app.vistas;

/**
 *
 * @author Eduardo
 */
public class ConfigFrame extends javax.swing.JFrame {

    /**
     * Creates new form ConfigFrame
     */
    public ConfigFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        monsterIP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        captchaKey = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        activeCaptcha = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        activeWorkers = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        bonusRP = new javax.swing.JCheckBox();
        bonoBTC = new javax.swing.JCheckBox();
        backgroundStatus = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        proxyPass = new javax.swing.JTextField();
        proxyUser = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebitcoin/app/images/capmonsterminipng.png"))); // NOI18N
        jLabel2.setText("CapMonster IP:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 120, 215));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Configuración");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebitcoin/app/images/icons8_Cancel_25px_2.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusable(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebitcoin/app/images/icons8_Cancel_25px_1.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebitcoin/app/images/icons8_Cancel_25px_1.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebitcoin/app/images/icons8_Cancel_25px_1.png"))); // NOI18N
        jButton1.setSelected(true);
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 3, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 525, 30));

        monsterIP.setBackground(new java.awt.Color(51, 51, 51));
        monsterIP.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        monsterIP.setForeground(new java.awt.Color(255, 255, 255));
        monsterIP.setText("127.0.0.3:80");
        jPanel1.add(monsterIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 98, 145, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebitcoin/app/images/icons8_Key_20px.png"))); // NOI18N
        jLabel3.setText("2Captcha:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 53, -1, -1));

        captchaKey.setBackground(new java.awt.Color(51, 51, 51));
        captchaKey.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        captchaKey.setForeground(new java.awt.Color(255, 255, 255));
        captchaKey.setText("6bb66728c813db2c10301d064aea5fea");
        jPanel1.add(captchaKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 50, 200, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Captcha Activo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 55, -1, -1));

        activeCaptcha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2Captcha", "CapMonster" }));
        jPanel1.add(activeCaptcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 55, 90, 20));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebitcoin/app/images/icons8_Workers_20px.png"))); // NOI18N
        jLabel5.setText("Mineros:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 100, 80, 20));

        activeWorkers.setModel(new javax.swing.SpinnerNumberModel(1, 1, 7, 1));
        jPanel1.add(activeWorkers, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 100, 70, -1));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        bonusRP.setBackground(new java.awt.Color(51, 51, 51));
        bonusRP.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        bonusRP.setForeground(new java.awt.Color(255, 255, 255));
        bonusRP.setText("Bonos Reward Point");
        jPanel1.add(bonusRP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 140, -1));

        bonoBTC.setBackground(new java.awt.Color(51, 51, 51));
        bonoBTC.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        bonoBTC.setForeground(new java.awt.Color(255, 255, 255));
        bonoBTC.setText("Bonos BTC");
        jPanel1.add(bonoBTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 110, -1));

        backgroundStatus.setBackground(new java.awt.Color(51, 51, 51));
        backgroundStatus.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        backgroundStatus.setForeground(new java.awt.Color(255, 255, 255));
        backgroundStatus.setText("Segundo Plano");
        jPanel1.add(backgroundStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 185, 490, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebitcoin/app/images/icons8_Checked_25px.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusable(false);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebitcoin/app/images/icons8_Checked_25px_1.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebitcoin/app/images/icons8_Checked_25px_1.png"))); // NOI18N
        jButton2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebitcoin/app/images/icons8_Checked_25px_1.png"))); // NOI18N
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 255, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebitcoin/app/images/icons8_Loyalty_Card_20px.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 202, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebitcoin/app/images/icons8_Bitcoin_20px.png"))); // NOI18N
        jLabel8.setLabelFor(bonoBTC);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 202, 30, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebitcoin/app/images/icons8_iMac_20px.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 202, -1, -1));

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/freebitcoin/app/images/icons8_Firewall_20px.png"))); // NOI18N
        jLabel10.setText("Proxy:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 145, -1, -1));

        proxyPass.setBackground(new java.awt.Color(51, 51, 51));
        proxyPass.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        proxyPass.setForeground(new java.awt.Color(255, 255, 255));
        proxyPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        proxyPass.setText("Contraseña");
        jPanel1.add(proxyPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 143, 90, -1));

        proxyUser.setBackground(new java.awt.Color(51, 51, 51));
        proxyUser.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        proxyUser.setForeground(new java.awt.Color(255, 255, 255));
        proxyUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        proxyUser.setText("Usuario");
        jPanel1.add(proxyUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 143, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> activeCaptcha;
    private javax.swing.JSpinner activeWorkers;
    private javax.swing.JCheckBox backgroundStatus;
    private javax.swing.JCheckBox bonoBTC;
    private javax.swing.JCheckBox bonusRP;
    private javax.swing.JTextField captchaKey;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField monsterIP;
    private javax.swing.JTextField proxyPass;
    private javax.swing.JTextField proxyUser;
    // End of variables declaration//GEN-END:variables
}
